/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BalanceValidatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "clearBalance"
      | "getEncryptedBalance"
      | "hasBalance"
      | "protocolId"
      | "setBalance"
      | "validateTransfer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BalanceCleared"
      | "BalanceSet"
      | "ValidationRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "clearBalance",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBalance",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTransfer",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "clearBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateTransfer",
    data: BytesLike
  ): Result;
}

export namespace BalanceClearedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BalanceSetEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationRequestedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BalanceValidator extends BaseContract {
  connect(runner?: ContractRunner | null): BalanceValidator;
  waitForDeployment(): Promise<this>;

  interface: BalanceValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  clearBalance: TypedContractMethod<
    [encryptedZero: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEncryptedBalance: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  hasBalance: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  setBalance: TypedContractMethod<
    [encryptedBalance: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  validateTransfer: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "clearBalance"
  ): TypedContractMethod<
    [encryptedZero: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasBalance"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setBalance"
  ): TypedContractMethod<
    [encryptedBalance: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateTransfer"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "BalanceCleared"
  ): TypedContractEvent<
    BalanceClearedEvent.InputTuple,
    BalanceClearedEvent.OutputTuple,
    BalanceClearedEvent.OutputObject
  >;
  getEvent(
    key: "BalanceSet"
  ): TypedContractEvent<
    BalanceSetEvent.InputTuple,
    BalanceSetEvent.OutputTuple,
    BalanceSetEvent.OutputObject
  >;
  getEvent(
    key: "ValidationRequested"
  ): TypedContractEvent<
    ValidationRequestedEvent.InputTuple,
    ValidationRequestedEvent.OutputTuple,
    ValidationRequestedEvent.OutputObject
  >;

  filters: {
    "BalanceCleared(address,uint256)": TypedContractEvent<
      BalanceClearedEvent.InputTuple,
      BalanceClearedEvent.OutputTuple,
      BalanceClearedEvent.OutputObject
    >;
    BalanceCleared: TypedContractEvent<
      BalanceClearedEvent.InputTuple,
      BalanceClearedEvent.OutputTuple,
      BalanceClearedEvent.OutputObject
    >;

    "BalanceSet(address,uint256)": TypedContractEvent<
      BalanceSetEvent.InputTuple,
      BalanceSetEvent.OutputTuple,
      BalanceSetEvent.OutputObject
    >;
    BalanceSet: TypedContractEvent<
      BalanceSetEvent.InputTuple,
      BalanceSetEvent.OutputTuple,
      BalanceSetEvent.OutputObject
    >;

    "ValidationRequested(address,uint256)": TypedContractEvent<
      ValidationRequestedEvent.InputTuple,
      ValidationRequestedEvent.OutputTuple,
      ValidationRequestedEvent.OutputObject
    >;
    ValidationRequested: TypedContractEvent<
      ValidationRequestedEvent.InputTuple,
      ValidationRequestedEvent.OutputTuple,
      ValidationRequestedEvent.OutputObject
    >;
  };
}
